app:
  image: node:4.1
  ports: [ "8080:8080" ]
  links: [ db ]
  volumes: [ "./:/app" ]
  working_dir: "/app"
  command: "bash -c \"npm install && npm run gulp nodemon\""
db:
  image: mongo:3.0
  volumes_from: [ dbdata ]
dbdata:
  image: busybox
  volumes: [ "/data/db" ]
  command: "true"
